### ISSUE TITLE
Fix Google analytics

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/monolith#103]
@zachlatta mentioned we were getting impossible results because the analytics code might still be in our iframe'd team and home pages.

**Comment by zachlatta** [comment]
So basically what happening is that we have significantly more AdWords clicks than Google Analytics sessions.
Which means people are clicking links to our website in our ads, but aren't properly being tracked by Google Analytics.
My guess is that Google Analytics isn't properly set up on the new site.
		
		

		
	




On Fri, Aug 11, 2017 at 10:38 AM -0700, "Max Wofford" <notifications@github.com> wrote:












@zachlatta mentioned we were getting impossible results because the analytics code might still be in our iframe'd team and home pages.

**Comment by zachlatta** [comment]
Ugh. Sorry about terrible formatting. Just tried changing my signature, does this fix the issue?
		
		

		-- 
Zach Latta
Hack Club | zach@hackclub.com
	




On Fri, Aug 11, 2017 at 2:16 PM -0700, <zach@hackclub.com> wrote:













	
		
		
	
		So basically what happening is that we have significantly more AdWords clicks than Google Analytics sessions.
Which means people are clicking links to our website in our ads, but aren't properly being tracked by Google Analytics.
My guess is that Google Analytics isn't properly set up on the new site.
		
		

		
	




On Fri, Aug 11, 2017 at 10:38 AM -0700, "Max Wofford" <notifications@github.com> wrote:












@zachlatta mentioned we were getting impossible results because the analytics code might still be in our iframe'd team and home pages.

**Comment by MaxWofford** [comment]
Yep! much better

**Comment by zachlatta** [comment]
Yay. It does. Will no longer be an issue in the future.
		
		

		-- 
Zach Latta
Hack Club | zach@hackclub.com
	




On Fri, Aug 11, 2017 at 2:20 PM -0700, <zach@hackclub.com> wrote:













	
		
		
	
		Ugh. Sorry about terrible formatting. Just tried changing my signature, does this fix the issue?
		
		

		-- 
Zach Latta
Hack Club | zach@hackclub.com
	




On Fri, Aug 11, 2017 at 2:16 PM -0700, <zach@hackclub.com> wrote:













	
		
		
	
		So basically what happening is that we have significantly more AdWords clicks than Google Analytics sessions.
Which means people are clicking links to our website in our ads, but aren't properly being tracked by Google Analytics.
My guess is that Google Analytics isn't properly set up on the new site.
		
		

		
	




On Fri, Aug 11, 2017 at 10:38 AM -0700, "Max Wofford" <notifications@github.com> wrote:












@zachlatta mentioned we were getting impossible results because the analytics code might still be in our iframe'd team and home pages.
